export enum AuthActionTypeKeys {
  SIGNIN_REQUEST = "SIGNIN_REQUEST",
  SIGNIN_SUCCESS = "SIGNIN_SUCCESS",
  SIGNIN_FAILURE = "SIGNIN_FAILURE",
  SIGNOUT_REQUEST = "SIGNOUT_REQUEST",
  SIGNOUT_SUCCESS = "SIGNOUT_SUCCESS",
  SIGNOUT_FAILURE = "SIGNOUT_FAILURE",
  VERIFY_REQUEST = "VERIFY_REQUEST",
  VERIFY_SUCCESS = "VERIFY_SUCCESS",
  VERIFY_FAILURE = "VERIFY_FAILURE",
  SIGNUP_REQUEST = "SIGNUP_REQUEST",
  SIGNUP_SUCCESS = "SIGNUP_SUCCESS",
  SIGNUP_FAILURE = "SIGNUP_FAILURE",
  ENTER_EMAIL = "ENTER_EMAIL",
  ENTER_PASSWORD = "ENTER_PASSWORD"
}
