export enum NotesActionTypeKeys {
  CLEAR_NOTES = "CLEAR_NOTES",
  ENTER_TEXT_NOTES = "ENTER_TEXT_NOTES",
  ENTER_HEADER_NOTES = "ENTER_HEADER_NOTES",
  SELECT_NOTES = "SELECT_NOTES",
  FETCH_NOTES = "FETCH_NOTES",
  CHECKED_NOTES = "CHECKED_NOTES",
  DELETE_NOTES = "DELETE_NOTES",
  ERROR_NOTES = "ERROR_NOTES",
  CLOSE_ERROR_DIALOG = "CLOSE_ERROR_DIALOG"
}
